// Render data/leaderboard.json into the published LEADERBOARD.md.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const data = JSON.parse(readFileSync("data/leaderboard.json", "utf8"));
const corpusSize = existsSync("data/corpus.json")
  ? JSON.parse(readFileSync("data/corpus.json", "utf8")).length
  : null;
const scored = data.results
  .filter((r) => r.status === "scored")
  .sort((a, b) => b.score - a.score || a.npm.localeCompare(b.npm));
const unreachable = data.results.filter((r) => r.status !== "scored");

const tier = (s) => (s >= 90 ? "🥇" : s >= 75 ? "🥈" : s >= 60 ? "🥉" : s >= 40 ? "" : "⚠️");
const date = data.generatedAt.slice(0, 10);

const L = [];
L.push("# 🏆 MCP Agent-Readiness Leaderboard", "");
L.push("> Every public MCP server in the [official registry](https://registry.modelcontextprotocol.io), booted and graded by [**mcp-scorecard**](https://github.com/davidmosiah/mcp-scorecard) on 10 agent-readiness checks (schema validity, tool naming, annotations, discovery surfaces, mutation gating, and more). Scored 0–100. Auto-refreshed weekly. Nothing here is hand-edited.", "");
const corpusNote = corpusSize ? ` of ${corpusSize} in the registry corpus` : "";
L.push(`**${scored.length} servers scored**${corpusNote} · ${unreachable.length} unreachable this run · updated ${date}`, "");
if (corpusSize && data.results.length < corpusSize) {
  L.push("", `> ⏳ Seed run. The weekly CI sweep scores the full ${corpusSize}-server corpus — this board grows on the next refresh.`);
}
const avg = scored.length ? Math.round(scored.reduce((s, r) => s + r.score, 0) / scored.length) : 0;
const top = scored[0];
L.push(`Ecosystem average: **${avg}/100**. Top server: **${top ? top.npm : "—"}** (${top ? top.score : 0}/100).`, "");
L.push("Tiers: 🥇 90+ · 🥈 75+ · 🥉 60+ · ⚠️ under 40", "");

L.push("| # | Server | Score | Biggest gap |");
L.push("|---:|---|---:|---|");
scored.forEach((r, i) => {
  const link = r.repo ? `[\`${r.npm}\`](${r.repo})` : `\`${r.npm}\``;
  L.push(`| ${i + 1} | ${link} ${tier(r.score)} | **${r.score}** | ${r.topGap || "—"} |`);
});
L.push("");

L.push("## Climb the board", "");
L.push("Score your own server and see the itemized fixes:", "", "```bash", "npx -y mcp-scorecard <your-package-or-repo>", "```", "");
L.push("Then add the live badge to your README so agents (and humans) see your score:", "", "```bash", "npx -y mcp-scorecard <your-package> --badge", "```", "");

L.push("## Methodology", "");
L.push("- Targets come from the official MCP registry (npm-installable servers only, latest active version).", "");
L.push("- Each server is booted over stdio in an isolated child process with a hard timeout. Servers that require auth before `listTools()` and don't honor the `MCP_PROBE` hook show as **unreachable** — not a low score, just not gradeable without credentials.", "");
L.push("- Scoring is shape/metadata/discoverability only. A server can score 100 and still return wrong data. This grades agent-*readiness*, not correctness. See [mcp-scorecard checks](https://github.com/davidmosiah/mcp-scorecard#what-it-checks).", "");

if (unreachable.length) {
  L.push("", "<details>", `<summary><b>${unreachable.length} unreachable</b> (auth-gated, install failure, or timeout)</summary>`, "");
  for (const r of unreachable.sort((a, b) => a.npm.localeCompare(b.npm))) {
    L.push(`- \`${r.npm}\` — ${r.status}${r.error ? `: ${r.error}` : ""}`);
  }
  L.push("</details>", "");
}

L.push("---", `<sub>Generated by [mcp-leaderboard](https://github.com/davidmosiah/mcp-leaderboard) · engine [mcp-scorecard](https://github.com/davidmosiah/mcp-scorecard) · ${data.generatedAt}</sub>`);

writeFileSync("LEADERBOARD.md", L.join("\n") + "\n");
console.log(`rendered LEADERBOARD.md — ${scored.length} ranked, ${unreachable.length} unreachable`);
